config/routes.rb
Blocipedia::Application.routes.draw do
 
  devise_for :users
  resources :wikis do 
    resources :collaborators, only: [:index, :create, :destroy]
  end
  resources :charges, only: [:new, :create]

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :wiki
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :wikis
  has_many :collaborators
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  default_scope { order('created_at DESC') }
  scope :not_private, -> { where("private IS NULL or private = ?", false) }
  scope :visible_to, -> (user) { user && user.premium? ? all : not_private }

  validates :title, length: { minimum: 1 }, presence: true
  validates :body, length: { minimum: 1 }, presence: true

  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  def should_generate_new_friendly_id?
    new_record?
  end

  def is_collaborator?(user)
    users.include?(user)
  end

  def collaborator_for(user)
    collaborators.where(user_id: user.id).first
  end

end

#Wiki.friendly.find(params[:id])

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  def after_sign_in_path_for(resource)
    wikis_path
  end

  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
      @stripe_btn_data = {
        key: "#{ Rails.configuration.stripe[:publishable_key] }",
        description: 'Premium Membership',
        amount: 1_299
      }
  end

  def create
      @amount = params[:amount]
      customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

      charge = Stripe::Charge.create(
      customer: customer.id, 
      amount: @amount,
      description: 'Premium Membership',
      currency: 'usd'
    )
 
      current_user.update_attribute(:premium, true)

      redirect_to wikis_path, flash: { notice: "Congratulations, #{current_user.email}, on becoming a premium member!"}

  rescue Stripe::CardError => e
     flash[:error] = e.message
     redirect_to new_charge_path
  end
end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_wiki

  def index
    @users = User.where("id is not ?", current_user.id)
  end

  def create
    @collaborator = @wiki.collaborators.build(user_id: params[:user_id])
    if @collaborator.save
      flash[:notice] = "You added a collaborator"
    else
      flash[:error] = "There was a problem creating this collaborator"
    end

    redirect_to wiki_collaborators_path(@wiki)
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "You removed a collaborator"
    else
      flash[:error] = "There was a problem removing this collaborator"
    end

    redirect_to wiki_collaborators_path(@wiki)
  end

  private

  def set_wiki 
    @wiki = Wiki.friendly.find(params[:wiki_id]) 
    #@wiki = Wiki.find(params[:wiki_id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController

  def index
    @wikis = Wiki.visible_to(current_user)
  end

  def show
    @wiki = Wiki.friendly.find(params[:id])
  end

  def new
    @wiki = Wiki.new
  end

  def create
     @wiki = current_user.wikis.build(wiki_params)
    
     if @wiki.save
       flash[:notice] = "Wiki was saved."
       redirect_to @wiki
     else
       flash[:error] = "There was an error saving the wiki. Please try again."
       render :new
     end
   end

  def edit
    @wiki = Wiki.friendly.find(params[:id])
  end

  def update
     @wiki = Wiki.friendly.find(params[:id])

     if @wiki.update_attributes(wiki_params)
       flash[:notice] = "Wiki was updated."
       redirect_to @wiki
     else
       flash[:error] = "There was an error saving the wiki. Please try again."
       render :edit
     end
   end

   def destroy
     @wiki = Wiki.friendly.find(params[:id])
    
     title = @wiki.title
 
     if @wiki.destroy
       flash[:notice] = "Wiki was deleted successfully."
       redirect_to wikis_path
     else
       flash[:error] = "There was an error deleting the wiki."
       render :show
     end
   end

   private

   def wiki_params
    params.require(:wiki).permit(:title, :body)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
   <%= hidden_field_tag :amount, @stripe_btn_data[:amount] %>
   <h4>Click the button to upgrade to premium!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/collaborators/index.html.erb
<h1>Collaborators for <%= @wiki.title %></h1>

<table class="table">
<% @users.each do |user| %>
  <tr>
    <td><%= user.name %></td>
    <td><%= user.email %></td>
    <td>
      <% if @wiki.is_collaborator?(user) %>
        <% collaborator = @wiki.collaborator_for(user) %>
        <%= link_to "Remove as collaborator", [@wiki, collaborator], method: :delete, class: "btn btn-danger" %>
      <% else %>
        <%= link_to "Add as  collaborator", wiki_collaborators_path(@wiki, user_id: user.id), method: :post, class: "btn btn-success" %>
      <% end %>
    </td>
  </tr>
 <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
 <body>

   <div class="container">
     <ul class="nav nav-tabs">
        <li><%= link_to "Blocipedia", root_path %></li>
        <li><%#= link_to "About", about_path %></li>
        <li><%= link_to "Wikis", wikis_path %></li>
        
   <div class="pull-right user-info">
        <% if current_user %>
          Hello <%= link_to current_user.email, edit_user_registration_path %>! 
          <%= link_to edit_user_registration_path, class: 'btn btn-primary btn-sm' do %>
          <span class="glyphicon glyphicon-user"></span>
        <% end %>

        <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-primary btn-sm' do %>
          <span class="glyphicon glyphicon-log-out"></span>
          <% end %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path %> or 
          <%= link_to "Sign Up", new_user_registration_path %>
        <% end %>
   </div>
  </ul>
  
  <% if flash[:notice] %>
         <div class="alert alert-success">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:notice] %>
         </div>
       <% elsif flash[:error] %>
         <div class="alert alert-danger">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:error] %>
         </div>
       <% elsif flash[:alert] %>
         <div class="alert alert-warning">
           <button type="button" class="close" data-dismiss="alert">&times;</button>
           <%= flash[:alert] %>
         </div>
       <% end %>

 <%= yield %>

 </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/welcome/about.html.erb
<h1>About Blocipedia</h1>
<p>Created by Valerie</p>

app/views/welcome/index.html.erb
<br/>
 <div class="jumbotron">
    <h1>Blocipedia</h1>
    <p>Use Blocipedia to create public and private Markdown-based wikis.</p>
    <p>
        <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> 
        <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> 
    </p>
 </div>

 <div class="row">
  <div class="col-md-4">
    <h2>User friendly</h2>
    <p>Manage your wikis with ease.</p>
 </div>

 <div class="col-md-4"> 
    <h2><%= link_to  "UPGRADE TO PREMIUM", new_charge_path, class: 'btn btn-primary btn' %></h2>
    <p>Create private wikis and add collaborators.</p><p>$12.99 for an annual subscription.</p>
 </div>

 <div class="col-md-4">
    <h2>No Ads</h2>
    <p>Blocipedia promises an ad free environment!</p>
 </div>
</div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
 
    <div class="row">
      <div class="col-md-4">
    </div>

    <div class="col-md-8">
       <%= form_for @wiki do |f| %>
     <div class="form-group">
       <%= f.label :title %>
       <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    </div>
         
    <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
    </div>
         
    <div class="form-group">
        <% if current_user.wikis.include?(@wiki) && current_user.premium? %>
        <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box(:private) %> Private wiki
        <% end %>
        <% end %>
    </div>

    <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
  <% end %>
 </div>
</div>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>

<% if current_user %>
  <p><%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %></p>
<% end %>

<% @wikis.each do |wiki| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <p><%= link_to wiki.title, wiki %></p>
      </h4>
      <small>
        created <%= time_ago_in_words(wiki.created_at) %> ago by <%= wiki.user.name %>
      </small>
     </div>
   </div>
<% end %>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
 
  <div class="row">
   <div class="col-md-4">
   </div>

   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>
       <div class="form-group">
         <% if current_user.wikis.include?(@wiki) && current_user.premium? %>
         <%= f.label :private, class: 'checkbox' do %>
         <%= f.check_box(:private) %> Private wiki
         <% end %>
        <% end %>
      </div>
      <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
   </div>
 </div>

app/views/wikis/show.html.erb
<div class="row">
  <div class="col-md-8">

   <h1><%= @wiki.title %></h1> 

      <% if current_user %>
        <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
      <% end %>

      <%# if current_user.wikis.include?(@wiki) %>
        <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %> 
      <%# end %>

      <% if current_user && current_user.premium? %>
         <%= link_to "Add/Remove Collaborators", wiki_collaborators_path(@wiki), class: 'btn btn-info' %>
      <% end %>
   
      <p><%= @wiki.body %></p>

</div>